<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Default bookmark settings' => 'Impostazioni predefinite segnalibri',
    'Here you can configure default settings for bookmark streams. These settings can be overwritten on profile level.' => 'Qui puoi configurare le impostazioni predefinite negli stream per i segnalibri. Queste impostazioni possono essere sovrascritte a livello di profilo.',
    'Here you can configure default settings for your bookmark stream.' => 'Qui puoi configurare le impostazioni predefinite per il tuo flusso di segnalibri.',
    'Reset' => 'Ripristina',
];
