<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Bookmark</strong> module configuration' => 'Configurazione del modulo <strong> Segnalibri </strong>',
    'Back to modules' => 'Torna ai moduli',
    'Bookmark view settings' => 'impostazioni di visualizzazione segnalibri',
    'Here you can change the view settings for bookmarks.' => 'Qui puoi modificare le impostazioni di visualizzazione per i segnalibri.',
    'Icon color' => 'Colore icona',
    'Select color' => 'Scegli il colore',
    'Show Bookmark-Count in braces.' => 'Mostra il conteggio dei segnalibri',
    'Show an icon for each entry.' => 'Mostra una icona per ogni segnalibro',
    'Show global Bookmark-View in full width.' => 'mostra la visualizzazione globale dei segnalibri a tutta larghezza.',
    'Show pinned content first.' => 'Mostra prima il contenuto in cima.',
    'Sort order' => 'Ordinamento',
];
